title: Feng Xiang
logo: /assets/img/headshot_img.JPG
description: AI Research Engineer
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Include custom CSS
head_scripts:
  - /video-embed.css
